### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by lotstar87** [things-factory/shell#13]
- [x] apptool-base
- [x] apptool-ui
- [x] attachment-base
- [x] attachment-ui
- [x] auth-base
- [x] auth-provider-jwt
- [x] auth-provider-session
- [x] auth-ui-jwt
- [x] auth-ui-session
- [x] barcode-base
- [x] barcode-ui
- [x] biz-base
- [x] biz-test
- [x] biz-ui
- [x] board-app
- [x] board-provider-gql
- [x] board-service
- [x] board-test
- [x] board-ui
- [x] code-base
- [x] code-test
- [x] component-ui
- [x] context-base
- [x] context-ui
- [x] cordova-plugin-ssdp
- [x] datasource-base
- [x] device-discover-node
- [x] env
- [x] export-base
- [x] export-ui
- [x] export-ui-csv
- [x] export-ui-excel
- [x] fav-base
- [x] file-base
- [x] font-base
- [x] font-ui
- [x] footer-base
- [x] form-ui
- [x] <strike>generator-things-factory</strike>
- [x] <strike>grist-ide</strike>
- [x] grist-test
- [x] grist-ui
- [x] i18n-base
- [x] i18n-ui
- [x] image-uploader-ui
- [x] import-base
- [x] import-ui
- [x] import-ui-csv
- [x] import-ui-excel
- [x] layout-base
- [x] layout-ui
- [x] live-chat-ui
- [x] menu-base
- [x] menu-provider
- [x] menu-test
- [x] menu-ui
- [x] more-base
- [x] more-ui
- [x] mqtt-base
- [x] offline-base
- [x] offline-ui
- [x] onpremise-proxy-service
- [x] onpremise-service
- [x] opa-app
- [x] opa-test
- [x] print-base
- [x] print-proxy-service
- [x] print-service
- [x] print-ui
- [x] product-base
- [x] provider-base-gql
- [x] publisher-base
- [x] publisher-service
- [x] publisher-ui
- [x] res-app
- [x] resource-base
- [x] resource-test
- [x] resource-ui
- [x] sales-base
- [x] screencast-base
- [x] screencast-proxy-service
- [x] screencast-ui
- [x] service-base
- [x] setting-base
- [x] setting-test
- [x] setting-ui
- [x] shell
- [x] state-base
- [x] system-base
- [x] system-ui
- [x] tester
- [x] <strike>things-factory-on-tv</strike>
- [x] <strike>things-factory.github.io</strike>
- [x] <strike>things-hybrid-ui</strike>
- [x] transport-base
- [x] warehouse-base
- [x] worksheet-base

**Comment by leemyunggyu** [comment]
image-uploader-ui 1.0.0 | 1.1.0

**Comment by lotstar87** [comment]
screencast-proxy-service 1.0.3 | 1.1.0

**Comment by lotstar87** [comment]
print-proxy-service 1.0.3 | 1.1.0

**Comment by lotstar87** [comment]
print-service 1.0.2 | 1.1.0

**Comment by lotstar87** [comment]
onpremise-service 1.0.2 | 1.1.0

**Comment by lotstar87** [comment]
onpremise-proxy-service 1.0.2 | 1.1.0

**Comment by heartyoh** [comment]
screencast-base 1.1.0 | 1.2.0

**Comment by lotstar87** [comment]
publisher-ui 1.0.11 | 1.1.0

**Comment by leemyunggyu** [comment]
screencast-ui 1.1.0 | 1.2.0
