### ISSUE TITLE
support nodejs v12

### ISSUE THREAD

**Issue by heartyoh** [things-factory/shell#15]
npm printer => npm node-native-printer 변경 검토.

**Comment by lllleeee** [comment]
https://github.com/MatteoMeil/node-native-printer/issues/25

**Comment by ghost** [comment]
node-native-printer도 같은 문제가 있으며, 문제 부분을 수정하고 다른 패키지로 묶어 재배포 필요

https://github.com/MatteoMeil/node-native-printer/issues/25

**Comment by ghost** [comment]
https://github.com/tojocky/node-printer/pull/261

wait for the merge or edit `package.json` to code below.
```json
{
  "dependencies": {
    "printer": "thiagoelg/node-printer#master"
  }
}
```

**Comment by ghost** [comment]
`yarn install` 실행 시에 `printer` 소스를 현재 노드 버전으로 자동으로 빌드해주지 않는 듯 함
수동으로 빌드해주거나 13버전을 사용해야 동작

**Comment by ghost** [comment]
https://github.com/things-factory/node-printer

**Comment by ghost** [comment]
프린터 출력을 위해 사용하는 모듈이 `printer`에서 `@things-factory/node-printer`로 변경되었습니다.
노드 버전 변경 후에는 작업할 프로젝트에서 yarn upgrade 실행 후 작업해야합니다.

이 이슈는 `printer` 모듈만 참조합니다.
