### ISSUE TITLE
fullbleed 일 때, snackbar가 보이지 않는 현상

### ISSUE THREAD

**Issue by lotstar87** [things-factory/shell#16]
### 원인
fullbleed이면 footer-bar를 hidden상태로 변경하는데, snackbar가 footer-bar에 속해있어 snackbar 역시 숨겨지게 됨.

### 개선방안
1. snackbar를 footer-bar에서 독립시킨다.
2. footer-bar를 hidden상태로 변경하는 것이 아닌, height를 0으로 변경한다.

**Comment by heartyoh** [comment]
분리하는게 좋겠군요.
