### ISSUE TITLE
Migration 실수 방지

### ISSUE THREAD

**Issue by lotstar87** [things-factory/shell#18]
# 목적
운영 DB에 migration하는 실수를 예방

# 시나리오
1. migration 실행시 mode 선택 (어떤 config 파일을 참조할 것인지 선택을 위해)
2. config - ormconfig에 host가 존재하면, host 값을 retype 하여 일치하면 migration 진행.

**Comment by lotstar87** [comment]
![avoid-migration-mistakes](https://user-images.githubusercontent.com/12129818/69216455-9b3efc00-0baf-11ea-8700-9a996a96fc8f.gif)

**Comment by heartyoh** [comment]
&#128077;
