### ISSUE TITLE
fullbleed일 때 overlay가 보이지 않는 현상

### ISSUE THREAD

**Issue by lotstar87** [things-factory/shell#19]
#16 과 같은 현상.

Overlay를 layout 요소로 부터 독립시켜야 함.

**Comment by heartyoh** [comment]
overlay도 layout 요소를 anchor로 이용해서 동작하도록 했기 때문에, 분리시키는 것은 많은 문제가 뒤따르기도 하겠고, 레이아웃팅의 기본 설계가 허물어지게 될 것으로 보이네요.
fullbleed 일 때의 header, nav, aside, footer를 display: none으로 하지 않고, overlay anchor외의 아이템들만 display: none 을 시키는 것으로 해결해봅시다.

**Comment by heartyoh** [comment]
https://github.com/things-factory/layout-ui/commit/9bfd8658a601c153e48e2762ef01f290d67503fb
