### ISSUE TITLE
workbox-webpack-plugin 5.0.0 적용

### ISSUE THREAD

**Issue by heartyoh** [things-factory/shell#41]

**Comment by lotstar87** [comment]
workbox-webpack-plugin v5 cause this error;

ERROR in You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer

> 추가    
    webpack.config.js에 sourcemap을 설정하면 위와 같은 에러가 발생함.

**Comment by lotstar87** [comment]
source-map 에러를 피하기 위해 source map을 cheap-module-source-map -> eval-cheap-module-source-map으로 변경.

변경 후, workbox-precache가 작동하지 않음 (파일 사이즈 제한 초과로 인해...)
